Consortium/Areas/Admin/ViewModels/UserTypeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Consortium.Areas.Admin.ViewModels
{
    public class UserTypeViewModel
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string StatusId { get; set; }
        public string Status { get; set; }
    }

    public class UserTypePartialViewModel
    {
        public string TypeId { get; set; }
        public string Option { get; set; }
        public IEnumerable<SelectListItem> Types { get; set; }
    }
}

Consortium/Areas/Admin/Controllers/UserTypeController.cs
using AutoMapper;
using Consortium.App_Code.Base;
using Consortium.App_Code.Filters;
using Consortium.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tier.Entity;
using Tier.Library.Common;
using Tier.Service;

namespace Consortium.Areas.Admin.Controllers
{
    [SessionTimeout]
    public partial class UserTypeController : _AbstractController
    {
        private UserTypeService _userTypeService;
        private StatusService _statusService;

        public UserTypeController()
        {
            _userTypeService = UserTypeService.Instance;
            _statusService = StatusService.Instance;
        }

        public ActionResult Index()
        {
            IEnumerable<UserType> userTypes = _userTypeService.GetAll();

            IEnumerable<UserTypeViewModel> model = Mapper.Map<IEnumerable<UserType>, IEnumerable<UserTypeViewModel>>(userTypes);

            model = model ?? (model = new List<UserTypeViewModel>());

            return View(model);
        }
    }

    [SessionTimeout]
    public partial class UserTypeController : _AbstractController
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Detail(int? id, UserTypeViewModel model)
        {
            ResponseMessageBuilder responseMessageBuilder = new ResponseMessageBuilder();

            if (!ModelState.IsValid)
            {
                ResponseError("Invalid ModelState");
                return Json(responseMessageBuilder.NoOk().Warning()
                    .ModelStateErrorsString(ModelState)
                    .Build(), JsonRequestBehavior.AllowGet);
            }

            UserType userType = id.HasValue && id.Value > 0 ? _userTypeService.Get(id.Value) : new UserType();

            userType.Code = Convert.ToInt32(model.Code);
            userType.Name = model.Name;
            userType.Description = model.Description;
            userType.Status = Convert.ToInt16(model.StatusId);
            userType.ResolveSecurityFields(SessionHandler.User.Id);


            _userTypeService.Save(userType);

            responseMessageBuilder.Ok().Success().Message("User type save successfully");

            return Json(responseMessageBuilder.Build(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            ResponseMessageBuilder responseMessageBuilder = new ResponseMessageBuilder();

            if (0 >= id)
            {
                return Json(responseMessageBuilder.Ok().Success()
                  .Message("Invalid user type id").Build(), JsonRequestBehavior.AllowGet);
            }

            UserType userType = _userTypeService.Get(id);

            if (null == userType || 0 >= userType.Id)
            {
                return Json(responseMessageBuilder.Ok().Success()
                  .Message("User type not found").Build(), JsonRequestBehavior.AllowGet);
            }

            userType.Status = (short)EnumStatus.Deleted;
            userType.ResolveSecurityFields(SessionHandler.User.Id);

            _userTypeService.Delete(userType);

            return Json(responseMessageBuilder.Ok().Success()
                .Message("User type deleted successfully").Build(), JsonRequestBehavior.AllowGet);
        }
    }
}

Consortium/Areas/Admin/Views/UserType/Index.cshtml
@model IEnumerable<Consortium.Areas.Admin.ViewModels.UserTypeViewModel>
@{
    ViewBag.Title = "Index";
}

@section Breadcrumbs {
    <li class="active">
        User Types
    </li>
}

@section PageHeader {
    User Types <small>user types list</small>
}

@section Styles {
    <link href="@Url.Content("~/Content/assets/plugins/select2/select2.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/assets/plugins/DataTables/media/css/DT_bootstrap.css")" rel="stylesheet" />

    <link href="@Url.Content("~/Content/assets/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/assets/plugins/bootstrap-modal/css/bootstrap-modal.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
    <!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
    <script src="@Url.Content("~/Content/assets/plugins/bootbox/bootbox.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/assets/plugins/jquery-mockjax/jquery.mockjax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/assets/plugins/select2/select2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/assets/plugins/DataTables/media/js/jquery.dataTables.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/assets/plugins/jquery-validation/dist/jquery.validate.min.js")"></script>
    <script src="@Url.Content("~/Areas/Admin/Content/js/esaw.userType.js")"></script>

    <script src="@Url.Content("~/Content/assets/plugins/bootstrap-modal/js/bootstrap-modal.js")"></script>
    <script src="@Url.Content("~/Content/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js")"></script>
    <!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
}

@section ScriptsImpl {

    <script type="text/javascript">
        var _ESAW = {
            userTypeForm: new ESAWForms.basic("#frmUserType", "@Url.Action("Detail", "UserType")",
                new ESAWMessengers.basic("#wrapper-message"), new ESAWAjaxLoader.basic("#modal-save", "ajax-loader")),
            userTypeFormValidations: {
                rules: {
                    "Code": { required: true },
                    "Name": { required: true }
                },
                messages: {
                    "Code": { required: "Code is a required field" },
                    "Name": { required: "Name is a required field" }
                }
            },


            deleteUserTypeForm: new ESAWForms.delete('@Url.Action("Delete", "UserType")',
                new ESAWMessengers.basic('#wrapper-message'), new ESAWAjaxLoader.basic('#modal-delete', 'ajax-loader')),

            loadUserTypesTable: new ESAWForms.load('#wrapper-user-types > #table > tbody', '@Url.Action("UserTypesList", "_RenderAction", new { option = "tbody-content" })',
                new ESAWMessengers.basic('#wrapper-message'), new ESAWAjaxLoader.withMessage('#wrapper-panel-user-types', 'ajax-loader-with-message', '<img src="/Content/assets/images/loading.gif" /> Loading...')),

            loadUserTypeForm: new ESAWForms.load('#modal-save #frmUserType', '@Url.Action("UserType", "_RenderAction", new { id = "_id_", option = "form-modal" })',
                new ESAWMessengers.basic('#modal-save #wrapper-message'), new ESAWAjaxLoader.basic('#modal-save', 'ajax-loader')),

            userTypesTable: new ESAWPlugins.dataTable("#table", {}),

            deleteModal: new ESAWModals.confirm('#modal-delete'),
            saveModal: new ESAWModals.confirmWithDynamicContent('#modal-save', '#frmUserType')
        };

    </script>

    <script type="text/javascript">
        $(function () {
            Main.init();
        });
    </script>
}

<!-- start: PAGE CONTENT -->
<div class="row">

    <div class="col-md-12">
        <div id="wrapper-message"></div>
    </div>

    <div class="col-md-12 space20">
        <a href="javascript:;" onclick="$.fn.userTypeJS('loadBy', this, 0)"><i class="fa fa-plus"></i> Add</a>
    </div>

    <div class="col-md-12">
        <!-- start: DYNAMIC TABLE PANEL -->
        <div id="wrapper-panel-user-types" class="panel panel-default" style="position:relative;">
            <div class="panel-heading">
                <i class="fa fa-external-link-square"></i>
                Users List
                <div class="panel-tools">
                    <a class="btn btn-xs btn-link panel-collapse collapses" href="#"> </a>
                    @*<a class="btn btn-xs btn-link panel-config" href="#panel-config" data-toggle="modal"> <i class="fa fa-wrench"></i> </a>*@
                    <a class="btn btn-xs btn-link panel-refresh" href="#" onclick="$.fn.userTypeJS('loadList', this)"> <i class="fa fa-refresh"></i> </a>
                    <a class="btn btn-xs btn-link panel-expand" href="#"> <i class="fa fa-resize-full"></i> </a>
                    @*<a class="btn btn-xs btn-link panel-close" href="#"> <i class="fa fa-times"></i> </a>*@
                </div>
            </div>
            <div id="wrapper-user-types" class="panel-body">

                @{ Html.RenderAction("UserTypesList", "_RenderAction", new { option = "table" }); }

            </div>
        </div>
        <!-- end: DYNAMIC TABLE PANEL -->
    </div>
</div>
<!-- end: PAGE CONTENT-->

<div id="modal-delete" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" style="display: none;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
        </button>
        <h4 class="modal-title">Delete User Type</h4>
    </div>
    <div class="modal-body">
        <p>
            Are you sure, do you want to delete user type?
        </p>
    </div>
    <div class="modal-footer">
        <button id="btnNo" type="button" data-dismiss="modal" class="btn btn-default">
            No
        </button>
        <button id="btnYes" type="button" class="btn btn-primary">
            Yes
        </button>
    </div>
</div>

<div id="modal-save" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false" style="display: none;">

    <div class="col-md-12">
        <div id="wrapper-message"></div>
    </div>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
        </button>
        <h4 class="modal-title">Save User Type</h4>
    </div>
    <div class="modal-body">

        <form id="frmUserType" action="@Url.Action("Save", "UserType")">

        </form>

    </div>
    <div class="modal-footer">
        <button id="btnSave" onclick="$.fn.userTypeJS('saveUserType', this)" type="button" class="btn btn-primary">
            Save
        </button>
        <button id="btnClose" type="button" data-dismiss="modal" class="btn btn-default">
            Close
        </button>
    </div>
</div>

Consortium/Areas/Admin/Views/UserType/_PartialUserType.cshtml
@model Consortium.Areas.Admin.ViewModels.UserTypeViewModel

@if ("form-modal".Equals(ViewBag.Option))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">
                    Code
                </label>
                <span class="input-icon">
                    @Html.TextBoxFor(m => m.Code, new { id = "Code", placeholder = "Code", @class="form-control" })
                    <i class="clip-checkmark"></i>
                </span>
            </div>
            <div class="form-group">
                <label class="control-label">
                    Name
                </label>
                <span class="input-icon">
                    @Html.TextBoxFor(m => m.Name, new { id = "Name", placeholder = "Name", @class = "form-control" })
                    <i class="clip-checkmark"></i>
                </span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">
                    Description
                </label>
                <span class="input-icon">
                    @Html.TextBoxFor(m => m.Description, new { id = "Description", placeholder = "Description", @class = "form-control" })
                    <i class="clip-checkmark"></i>
                </span>
            </div>

            <div class="form-group">
                <label class="control-label">
                    Status
                </label>

                @{ Html.RenderAction("Statuses", "_RenderAction", new { id = Model.StatusId, option = "select" }); }
                @*@Html.DropDownListFor(m => m.StatusId, Model.Statuses, new { @class = "form-control" })*@
            
            </div>

        </div>
    </div>
}

Consortium/Areas/Admin/Views/UserType/_PartialUserTypes.cshtml
@model Consortium.Areas.Admin.ViewModels.UserTypePartialViewModel

@if ("select".Equals(Model.Option))
{
    @Html.DropDownListFor(m => m.TypeId, Model.Types, new { @class = "form-control" })
}

Consortium/Areas/Admin/Views/UserType/_PartialUserTypesList.cshtml
@model IEnumerable<Consortium.Areas.Admin.ViewModels.UserTypeViewModel>

@if ("table".Equals(ViewBag.Option))
{
<table id="table" class="table table-striped table-bordered table-hover table-full-width">
    <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Description</th>
            <th>Status</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var userType in Model)
        {
            <tr>
                <td>@userType.Code</td>
                <td>@userType.Name</td>
                <td>@userType.Description</td>
                <td>@userType.Status</td>
                <td>
                    <a href="javascript:;" onclick="$.fn.userTypeJS('loadBy', this, @userType.Id)"><i class="fa fa-edit"></i> Edit</a>
                    &nbsp;
                    <a href="javascript:;" onclick="$.fn.userTypeJS('confirmDelete', this, @userType.Id)"><i class="fa fa-trash-o"></i> Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
}
else if ("tbody-content".Equals(ViewBag.Option))
{
    foreach (var userType in Model)
    {
        <tr>
            <td>@userType.Code</td>
            <td>@userType.Name</td>
            <td>@userType.Description</td>
            <td>@userType.Status</td>
            <td>
                <a href="javascript:;" onclick="$.fn.userTypeJS('loadBy', this, @userType.Id)"><i class="fa fa-edit"></i> Edit</a>
                &nbsp;
                <a href="javascript:;" onclick="$.fn.userTypeJS('confirmDelete', this, @userType.Id)"><i class="fa fa-trash-o"></i> Eliminar</a>
            </td>
        </tr>
    }
}

<!-- end: PAGE CONTENT-->